[CONFIG #5 ] JWT, OAuth 로그인
farmtedPlaydata/farmted-Repo pull request #16
Opened 2023-11-16 05:21 UTC by JinDalgi

수정해야 할 사안
 - JwtFilter -> API Gateway로 이동
 - OAuth2 로그인 시 자체 토큰 발급

2023-11-16 05:45 UTC, Hwater00 commented on auth-service/src/main/java/com/farmted/authservice/domain/Pass.java
>      private String uuid;
@NotNull을 사용하는 편이 좋을 것 같습니다. [아래 설명 자세히 보기](https://kafcamus.tistory.com/15)

이유 1)@NotNull 어노테이션을 쓰면, 데이터베이스에 SQL 쿼리를 보내기 전에 예외가 발생합니다.
JPA의 Repository 인터페이스가 잘못된 Entity를 저장할 때, ConstraintViolationException을 발생시키는데
(그 때문에, @Valid나 @Validated 없이도 엔티티를 자연스럽게 검증할 수 있습니다.)

이유2) @Column에서 nullable=false를 제거해도, @NotNull이 붙어있으면 DDL 생성 시 not null로 생성

2023-11-16 06:01 UTC, Hwater00 approved these changes

2023-11-16 06:04 UTC, Taehk requested changes
코드리뷰 했습니다 확인해주세용
그냥 추가 질문 : 
1. Security Config에 // X-Frame-Options 헤더 비활성화는 OAuth 구현에 필요한 옵션인가여?
2. 리프레시 토큰을 쿠키에 담는 이유가 뭐였죠?

2023-11-16 06:08 UTC, JinDalgi commented on auth-service/src/main/java/com/farmted/authservice/domain/Pass.java
>      private String uuid;
넹 수정해놓을게요

2023-11-16 06:10 UTC, Hwater00 commented on auth-service/src/main/java/com/farmted/authservice/service/PassServiceImpl.java
>          Pass pass = passRepository.findByEmail(dto.getEmail());
차후 부분에서 이메일에 해당하는 사용자를 찾지 못한 경우의 예외  처리 진행해주세요~

2023-11-16 06:28 UTC, MEL1902 approved these changes
JWT , Auth,Redis,Encoder 등 쿠키 속성 설정등
  확인했습니다!

2023-11-16 06:43 UTC, JinDalgi commented
> 코드리뷰 했습니다 확인해주세용 그냥 추가 질문 :
> 
> 1. Security Config에 // X-Frame-Options 헤더 비활성화는 OAuth 구현에 필요한 옵션인가여?
> 2. 리프레시 토큰을 쿠키에 담는 이유가 뭐였죠?

1. iframe = 웹 브라우저 내에 또 다른 프레임, 현재 브라우저에 렌더링되고있는 문서 안에 또 다른 HTML 페이지를 삽일할 수 있도록 하는 기능을 제공한다고 되어있는데 사용하지 않을 것 같아서 + 사용한다면 그에 맞춰 설정을 해주어야하는데 현재 페이지가 구성되어있지 않아서 비활성화 해두었습니다
2. 현재 리프레시 토큰을 쿠키에 담아서 존재한다면 엑세스 토큰을 재발급, 로그아웃 시 두 쿠키 모두 삭제하는 것을 완료한 다음에 수정하려고 합니다,
이유 = 엑세스 토큰이 만료되기 전에 리프레시토큰을 참조하여 엑세스 토큰을 재발급하는 것은 가능한데 엑세스 토큰이 만료된다면 사용자에 대한 정보가 남아있지 않아 인가된 사용자라는 것이 입증되지 않기 때문에 리프레시 토큰을 참조해서 엑세스 토큰을 재발급하는 부분까지 넘어가질 않습니다.
그래서 생각해 본 것이 AccessToken의 만료 기간을 10분 정도로 해두고 다른 서비스를 이용할 때 마다 재발급을 해주거나 AccessToken이 만료되더라도 UserDetails와 같이 로그인 한 사용자의 정보를 가지는 방법을 생각해보았는데
전자의 경우에는 다른 서비스를 이용할 때 마다 AccessToken을 재발급한다면 토큰 발급에 있어 너무 많은 데이터를 주고받게되어 비효율적이라고 생각했고
두번째 방법은 SecurityContextHolder에도 담아보고 UserDetails로 불러와보아도 AccessToken이 이미 만료된 후라 사용자의 정보를 가져올 수 없었습니다.
만약 하게 된다면 프론트에서 사용자의 정보를 갖고 AccessToken이 만료되었을 경우 그 사용자의 uuid 또는 email같은 값을 서버로 보내주고, 그 값을 참조해서 새로운 AccessToken을 재발급 해주는 방법이 좋지 않을까 생각했습니다

2023-11-16 06:44 UTC, JinDalgi commented on auth-service/src/main/java/com/farmted/authservice/domain/Pass.java
넹

2023-11-16 06:44 UTC, Taehk approved these changes

2023-11-16 06:45 UTC, JinDalgi commented on auth-service/src/main/java/com/farmted/authservice/controller/PassController.java
수정했습니다

2023-11-17 01:28 UTC, Taehk requested changes
Test

2023-11-17 01:30 UTC, Taehk approved these changes

2023-11-17 01:32 UTC, Taehk approved these changes

2023-11-17 12:41 UTC, merged